services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/app
        environment:
            - MONGO_HOST=mongodb
            - MONGO_PORT=27017
            - TZ=UTC

    frontend:
        image: caddy:latest
        volumes:
            - ./frontend/Caddyfile:/etc/caddy/Caddyfile
            - ./frontend:/var/www/html
        ports:
            - "80:80"
        restart: on-failure
        depends_on:
            - backend

    mongodb:
        build:
            context: ./mongodb
            dockerfile: Dockerfile
        ports:
            - "27017:27017"
        expose:
            - "27017"
        volumes:
            - ./mongodb/data:/data/db
        depends_on:
            - backend
